# Lower computation cost: random
- RandomSamplingDataPointsFilter:
    prob: 0.4

# Higher computation cost: spatial representation of the pointcloud by the octree to sub-sample point in each leaf
# - OctreeGridDataPointsFilter:
#     buildParallel: 1
#     maxPointByNode: 1
#     maxSizeByNode: 0.05
#     samplingMethod: 1
