name: spf-venv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cupy
  - ffmpeg
  - numpy
  - pillow
  - pytest
  - python=3.8
  - pytorch>=1.10
  - torchvision
  - matplotlib
  - pandas
  - tensorboard
  - tqdm
  - pip
  - ruamel.yaml
  - pip:
      - opencv-python