nimbro_anymal_missionctrl_sender: &nimbro_anymal_missionctrl_sender
  tcp_topics:
    - name: "/nimbro_anymal_missionctrl_action_follow/remote/result" # action feedback & status are sent over UDP to allow rate control.
    - name: "/local_guidance_path_manager/received_global_path"
    - name: "/on_demand_elevation_map/map"
      compress: true
    - name: "/on_demand_lidar1/point_cloud/draco"
    - name: "/on_demand_lidar2/point_cloud/draco"
    - name: "/on_demand_loam/full_path"
    - name: "/on_demand_loam/map/draco"
    - name: "/on_demand_loam/submap/draco"
    - name: "/vis/geofence"
    - name: "/darpa_locomotion_mission_bt/homing_timer"
    - name: "/darpa_locomotion_mission_bt/status"
    - name: "/darpa_locomotion_mission_bt/robot_is_moving"
    - name: "/gbplanner/go_to_waypoint_pose_visualization"
    - name: "/bayesian_artifact_filter/filtered_artifact"
    - name: "/incremental_map_update/point_cloud/draco"
    - name: "/submap_counter"
  udp_topics:
    - name: "/artifact_camera/image/compressed"
      low_priority_topic: true
    - name: "/artifact_camera_2/image/compressed"
      low_priority_topic: true
    - name: "/artifact_camera_3/image/compressed"
      low_priority_topic: true
    - name: "/artifact_camera_4/image/compressed"
      low_priority_topic: true
    - name: "/darpa_locomotion_mission_bt/active_client"
      rate: 1.0
    - name: "/darpa_locomotion_mission_bt/active_client_path"
      rate: 1.0
    - name: "/nimbro_anymal_missionctrl_action_follow/remote/feedback"
      rate: 1.0
      low_priority_topic: true
    - name: "/nimbro_anymal_missionctrl_action_follow/remote/status"
      rate: 1.0
      low_priority_topic: true
    - name: "/tf_selective_snapshooter/tf_snapshot"
    - name: "/darpa_locomotion_mission/mission_state"
      rate: 1.0
    - name: "/darpa_locomotion_mission_bt/available_wifi_beacons"
      rate: 0.2
      low_priority_topic: true
    - name: "/safety_checker/traversabiliy_safety_status"
      rate: 1.0
      low_priority_topic: true
    - name: "/local_guidance_path_follower/controller_reference_marker"
      rate: 1.0
      low_priority_topic: true
    - name: "/distance_tracker/display"
      rate: 0.5
      low_priority_topic: true
    - name: "/ping_monitor_anymal/markers"
      rate: 0.2
      low_priority_topic: true
    - name: "/msf_loam_alphasense_imu/msf_core/odometry"
      rate: 1.0
    - name: "/msf_loam_body_imu/msf_core/odometry"
      rate: 1.0
    - name: "/msf_core/odometry_in_darpa"
    - name: "/tf/base_subt_to_darpa_in_darpa"
      rate: 3.0

nimbro_robot_transfolder_missionctrl_tcp_client:
  services:
    - name: /transfolder/file_transfer_status
      type: transfolder_msgs/FileTransferStatus

nimbro_missionctrl_anymal_tcp_client: &nimbro_missionctrl_anymal_tcp_client
  services:
    - name: /darpa_locomotion_mission_bt/automatic_planning
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/trigger_homing
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/stop_planning
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/cancel_all_goals
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/set_homing_timer
      type: any_msgs/SetFloat64
    - name: /gbplanner/set_global_bound
      type: planner_msgs/planner_set_global_bound
    - name: /darpa_locomotion_mission_bt/enable_safe_locomotion
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/enable_local_planner
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/enable_wifi_safety
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/enable_traversability_safety
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/go_to_waypoint
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/go_to_waypoint_and_explore
      type: any_msgs/SetFloat64
    - name: /darpa_locomotion_mission_bt/recovery_homing
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/trigger_user_inspection
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/trigger_user_point_inspection
      type: std_srvs/Trigger
    - name: /darpa_locomotion_mission_bt/enable_automatic_full_scans
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/enable_automatic_point_scans
      type: std_srvs/SetBool
    - name: /darpa_locomotion_mission_bt/deploy_wifi_beacon
      type: std_srvs/Trigger
    - name: "/darpa_locomotion_mission_bt/follow_path_and_explore"
      type: darpa_subt_anymal_msgs/AnymalFollowPathAndExplore
    - name: "/on_demand_lidar1/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_lidar2/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_elevation_map/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_loam_full_path/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_loam_full_path_optimized/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_loam_map/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_loam_submap/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/on_demand_loam_map_optimized/publish_next_incoming_message"
      type: std_srvs/Empty
    - name: "/darpa_frame_save_load_slave/load_tf_frame_from_default_file"
      type: std_srvs/Trigger
    - name: "/elevation_mapping/clear_map_with_initializer"
      type: std_srvs/Empty
    - name: "/motion_control_manager/clear_emergency_stop"
      type: std_srvs/Empty
    - name: "/motion_control_manager/emergency_stop"
      type: std_srvs/Empty
    - name: "/gbplanner/clear_untraversable_zones"
      type: std_srvs/Trigger
    - name: "/image_to_map/reproject_manual"
      type: "image_to_map_msgs/get_point_from_roi"
    - name: "/local_guidance_path_manager/activate_forced_stop_following_path"
      type: std_srvs/Trigger
    - name: "/local_guidance_path_manager/release_forced_stop_following_path"
      type: std_srvs/Trigger
    - name: "/gbplanner/set_dynamic_global_bound"
      type: planner_msgs/planner_dynamic_global_bound
    - name: "/go_idle"
      type: std_srvs/Empty
    - name: "/nimbro_anymal_missionctrl_sender/enable_sending_low_priority_topics"
      type: std_srvs/Trigger
    - name: "/nimbro_anymal_missionctrl_sender/disable_sending_low_priority_topics"
      type: std_srvs/Trigger
    - name: "/transfolder/set_max_num_batched_subfolders_high"
      type: std_srvs/SetBool

nimbro_missionctrl_anymal_sender: &nimbro_missionctrl_anymal_sender
  tcp_topics:
    - name: "/nimbro_missionctrl_anymal_action_follow/remote/goal"
    - name: "/nimbro_missionctrl_anymal_action_follow/remote/cancel"
    - name: "/global_planner/waypoint_request"
    - name: "/test_topic_mission_control_to_anymal_pc"
    - name: "/yolo_ack"
    - name: "/graph_monitor/sparse_graph/graph"
    - name: "/graph_monitor/sparse_graph/trajectory"
    - name: "/graph_monitor/submaps"
    - name: "/inspection_head/scan_point"

# Mission Control Center
nimbro_missionctrl_anymal_1_sender:
  <<: *nimbro_missionctrl_anymal_sender

nimbro_missionctrl_anymal_2_sender:
  <<: *nimbro_missionctrl_anymal_sender

nimbro_missionctrl_anymal_3_sender:
  <<: *nimbro_missionctrl_anymal_sender

nimbro_missionctrl_anymal_4_sender:
  <<: *nimbro_missionctrl_anymal_sender

nimbro_missionctrl_anymal_5_sender:
  <<: *nimbro_missionctrl_anymal_sender

## ANYmal 1
nimbro_sim_anymal_1_missionctrl_sender:
  <<: *nimbro_anymal_missionctrl_sender

nimbro_missionctrl_anymal_1_tcp_client:
  <<: *nimbro_missionctrl_anymal_tcp_client

## ANYmal 2
nimbro_sim_anymal_2_missionctrl_sender:
  <<: *nimbro_anymal_missionctrl_sender

nimbro_missionctrl_anymal_2_tcp_client:
  <<: *nimbro_missionctrl_anymal_tcp_client

## ANYmal 3
nimbro_missionctrl_anymal_3_tcp_client:
  <<: *nimbro_missionctrl_anymal_tcp_client

## ANYmal 4
nimbro_missionctrl_anymal_4_tcp_client:
  <<: *nimbro_missionctrl_anymal_tcp_client

## ANYmal 5
nimbro_missionctrl_anymal_5_tcp_client:
  <<: *nimbro_missionctrl_anymal_tcp_client
