local_guidance_controllers:
  controllers:
    nop:
      controller_class_name:                              nop
      lookahead_distance:                                 0.0
    pid_normal:
      lookahead_distance:                                 1.0
      lookahead_rotation:                                 0.43
      linear_velocity_should_be_saturated:                true
      angular_velocity_should_be_saturated:               true
      lock_lookahead_pose_based_on_linear_distance:       false
      lock_lookahead_pose_based_on_rotational_distance:   true
      tolerance_to_switch_desired_pose:
        translation: 0.15
        rotation: 0.1
      longitudinal_controller:    # Controls the forward (longitudinal) motion.
        proportional_gain:                                0.9
        integral_gain:                                    0.0
        derivative_gain:                                  0.15
        max_effort:                                       0.5
        max_integrator_input:                             0.3
        switching_direction_threshold_velocity:           0.05
      lateral_controller:         # Controls the lateral (not the yaw) motion.
        proportional_gain:                                0.9
        integral_gain:                                    0.0
        derivative_gain:                                  0.1
        max_effort:                                       0.2
        max_integrator_input:                             0.3
      heading_controller:         # Controls the heading (yaw) of the robot.
        proportional_gain:                                0.65
        integral_gain:                                    0.0
        max_effort:                                       0.4
        max_integrator_input:                             0.174 # 10 degs to rads.
    pid_normal_learning:
      lookahead_distance:                                 1.0
      lookahead_rotation:                                 0.43
      linear_velocity_should_be_saturated:                true
      angular_velocity_should_be_saturated:               true
      lock_lookahead_pose_based_on_linear_distance:       false
      lock_lookahead_pose_based_on_rotational_distance:   true
      tolerance_to_switch_desired_pose:
        translation: 0.15
        rotation: 0.15
      longitudinal_controller:    # Controls the forward (longitudinal) motion.
        proportional_gain:                                1.0
        integral_gain:                                    0.0
        derivative_gain:                                  0.0
        max_effort:                                       1.0
        max_integrator_input:                             0.3
        switching_direction_threshold_velocity:           0.05
      lateral_controller:         # Controls the lateral (not the yaw) motion.
        proportional_gain:                                1.0
        integral_gain:                                    0.0
        derivative_gain:                                  0.0
        max_effort:                                       1.0
        max_integrator_input:                             0.3
      heading_controller:         # Controls the heading (yaw) of the robot.
        proportional_gain:                                2.0
        integral_gain:                                    0.0
        max_effort:                                       1.0
        max_integrator_input:                             0.174 # 10 degs to rads.
    pid_normal_learning_perceptive:
      lookahead_distance:                                 1.0
      lookahead_rotation:                                 0.17
      linear_velocity_should_be_saturated:                true
      angular_velocity_should_be_saturated:               true
      lock_lookahead_pose_based_on_linear_distance:       false
      lock_lookahead_pose_based_on_rotational_distance:   true
      tolerance_to_switch_desired_pose:
        translation: 0.15
        rotation: 0.15
      longitudinal_controller:    # Controls the forward (longitudinal) motion.
        proportional_gain:                                1.0
        integral_gain:                                    0.0
        derivative_gain:                                  0.0
        max_effort:                                       0.7
        max_integrator_input:                             0.3
        switching_direction_threshold_velocity:           0.05
      lateral_controller:         # Controls the lateral (not the yaw) motion.
        proportional_gain:                                1.0
        integral_gain:                                    0.0
        derivative_gain:                                  0.0
        max_effort:                                       0.5
        max_integrator_input:                             0.3
      heading_controller:         # Controls the heading (yaw) of the robot.
        proportional_gain:                                2.0
        integral_gain:                                    0.0
        max_effort:                                       1.0
        max_integrator_input:                             0.174 # 10 degs to rads.
    pure_pursuit_fast:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      desired_absolute_value_linear_velocity:             0.4
      abs_max_angular_velocity:                           0.25
      lateral_controller:
        max_effort:                                       0.2
    pure_pursuit_normal:
      controller_class_name:                              pure_pursuit
      lookahead_distance:                                 1.0   # Forward distance on the path where to place current goal [m].
      desired_absolute_value_linear_velocity:             0.3
      abs_max_angular_velocity:                           0.2
      rotation_z_body_control_deg:                        0.0  # This controller moves forward, no rotation form body to control frame.
      multiplier_angular_velocity_command:                1.0
      lateral_controller:
        proportional_gain:                                1.0
        max_effort:                                       0.2
      precisely_reach_last_goal_on_path:
        radius_ball_for_activation:                       0.4
        heading_controller:         # Controls the heading (yaw) of the robot.
          proportional_gain:                              1.0
          integral_gain:                                  0.01
          max_effort:                                     0.35
          max_integrator_input:                           0.174 # 10 degs to rads.
        longitudinal_controller:    # Controls the forward (longitudinal) motion.
          proportional_gain:                              0.5
          integral_gain:                                  0.05
          max_effort:                                     0.2
          max_integrator_input:                           0.3
          switching_direction_threshold_velocity:         0.05
        lateral_controller:         # Controls the lateral (not the yaw) motion.
          proportional_gain:                              0.5
          integral_gain:                                  0.05
          max_effort:                                     0.2
          max_integrator_input:                           0.3
    pure_pursuit_running:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      desired_absolute_value_linear_velocity:             0.5
      abs_max_angular_velocity:                           0.4
    pure_pursuit_slow:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      desired_absolute_value_linear_velocity:             0.15
      abs_max_angular_velocity:                           0.18
      lateral_controller:
        max_effort:                                       0.1
      precisely_reach_last_goal_on_path:
        heading_controller:         # Controls the heading (yaw) of the robot.
          max_effort:                                     0.2
        longitudinal_controller:    # Controls the forward (longitudinal) motion.
          max_effort:                                     0.05
      #test_param_overlay:                                 pure_pursuit_slow
    pure_pursuit_normal_backwards:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      lookahead_distance:                                 0.3
      rotation_z_body_control_deg:                        -180.0  # This controller moves backwards
      #test_param_overlay:                                 pure_pursuit_slow_reverse_gear
    pure_pursuit_normal_sideways_left:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      rotation_z_body_control_deg:                        90.0  # This controller moves left sideways
      #test_param_overlay:                                 pure_pursuit_slow_sideways_left
    pure_pursuit_normal_sideways_right:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      rotation_z_body_control_deg:                        -90.0  # This controller moves right sideways
      #test_param_overlay:                                 pure_pursuit_slow_sideways_right
    pure_pursuit_perceptive_3d_trot:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_normal
      desired_absolute_value_linear_velocity:             0.29
      abs_max_angular_velocity:                           0.37
    pure_pursuit_deep_learning:
      controller_class_name:                              pure_pursuit
      lookahead_distance:                                 1.0   # Forward distance on the path where to place current goal [m].
      desired_absolute_value_linear_velocity:             0.6
      abs_max_angular_velocity:                           1.0
      rotation_z_body_control_deg:                        0.0   # This controller moves forward, no rotation form body to control frame.
      multiplier_angular_velocity_command:                1.0
      linear_velocity_should_be_saturated:                true
      angular_velocity_should_be_saturated:               true
      lateral_controller:
        proportional_gain:                                2.0
        max_effort:                                       1.0
      precisely_reach_last_goal_on_path:
        radius_ball_for_activation:                       0.6
        heading_controller:         # Controls the heading (yaw) of the robot.
          proportional_gain:                              0.8
          integral_gain:                                  0.0
          max_effort:                                     1.0
          max_integrator_input:                           0.174 # 10 degs to rads.
        longitudinal_controller:    # Controls the forward (longitudinal) motion.
          proportional_gain:                              0.2
          integral_gain:                                  0.0
          derivative_gain:                                0.35
          max_effort:                                     1.0
          max_integrator_input:                           0.3
          switching_direction_threshold_velocity:         0.05
        lateral_controller:         # Controls the lateral (not the yaw) motion.
          proportional_gain:                              0.5
          integral_gain:                                  0.0
          max_effort:                                     1.0
          max_integrator_input:                           0.3
    pure_pursuit_deep_learning_backwards:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_deep_learning
      lookahead_distance:                                 0.3
      rotation_z_body_control_deg:                        -180.0  # This controller moves backwards
    pure_pursuit_deep_learning_perceptive:
      controller_class_name:                              pure_pursuit
      lookahead_distance:                                 1.0   # Forward distance on the path where to place current goal [m].
      desired_absolute_value_linear_velocity:             0.7
      abs_max_angular_velocity:                           1.0
      rotation_z_body_control_deg:                        0.0   # This controller moves forward, no rotation form body to control frame.
      multiplier_angular_velocity_command:                1.0
      linear_velocity_should_be_saturated:                true
      angular_velocity_should_be_saturated:               true
      lateral_controller:
        proportional_gain:                                1.0
        max_effort:                                       0.7
      precisely_reach_last_goal_on_path:
        radius_ball_for_activation:                       0.6
        heading_controller:         # Controls the heading (yaw) of the robot.
          proportional_gain:                              1.2
          integral_gain:                                  0.0
          max_effort:                                     1.0
          max_integrator_input:                           0.174 # 10 degs to rads.
        longitudinal_controller:    # Controls the forward (longitudinal) motion.
          proportional_gain:                              1.3
          integral_gain:                                  0.0
          derivative_gain:                                0.35
          max_effort:                                     0.5
          max_integrator_input:                           0.3
          switching_direction_threshold_velocity:         0.05
        lateral_controller:         # Controls the lateral (not the yaw) motion.
          proportional_gain:                              1.0
          integral_gain:                                  0.0
          max_effort:                                     0.5
          max_integrator_input:                           0.3
    pure_pursuit_deep_learning_perceptive_backwards:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_deep_learning_perceptive
      lookahead_distance:                                 0.3
      rotation_z_body_control_deg:                        -180.0  # This controller moves backwards
    pure_pursuit_deep_learning_perceptive_stairs:
      controller_class_name:                              pure_pursuit
      parameters_from_other_local_guidance_controller:    pure_pursuit_deep_learning_perceptive
      lookahead_distance:                                 1.2   # Forward distance on the path where to place current goal [m].
      desired_absolute_value_linear_velocity:             0.9
