gbplanner_node:
  inspection_head: true
stack_launcher:
  stacks:
    apc_subt:
      stacks:
        apc_drivers:
          enabled: true
        inspection_head_stack:
          enabled: true
    artifact_detection_tensorrt_combined_subt:
      nodes:
        tensorrt_artifact_detection_zoom_camera:
          enabled: true
    artifact_detection_tensorrt_single_instances_subt:
      nodes:
        tensorrt_artifact_detection_zoom_camera:
          enabled: true
    npc_subt:
      stacks:
        apc_drivers:
          enabled: true
        inspection_head_stack:
          enabled: true
    replay_basic_subt:
      nodes:
        inspection_payload_robot_state_publisher:
          enabled: true