input_channel: 4
input_height: 500
input_width: 720
norm: linear
min_depth: 0.001
max_depth: 10
min_depth_eval: 0.001
max_depth_eval: 10
max_pc_depth: 15
normalize_output_mean: 0.12
normalize_output_std: 1.17
deactivate_bn: true
skip_connection: false
interpolate_mode: bilinear
output_mask: true
decoder_num: 1
ablation: 1decoder
