wandb_name: noskip_1decoder
bs: 6
workers: 16
dataset: anymal
slim_dataset: true
pc_img_input_channel: 0
pc_img_label_channel: 0
lr: 0.000357
wd: 0.1
div_factor: 25
final_div_factor: 100
epochs: 30
data_path: extract_trajectories
camera_cali_path: /semantic_front_end_filter/Labelling/Example_Files/alphasense
do_random_rotate: true
degree: 1.0
do_kb_crop: true
garg_crop: true
eigen_crop: true
random_crop: true
random_flip: true
traj_variance_threashold: 1
validate_every: 100
same_lr: true
use_right: false
pc_image_label_W: 1
traj_label_W_4mask: 1
traj_label_W: 0.02
edge_aware_label_W: 0
consistency_W: 0
mask_loss_W: 1
mask_regulation_W: 0
mask_regulation_CE_W: 0.0
mask_weight_mode: sigmoid
filter_image_before_loss: true
sprase_traj_mask: false
mask_ratio: 1
traj_distance_variance_ratio: 0
pc_label_uncertainty: false
scale_loss_with_point_number: true
train_with_sample: false
testing:
- Reconstruct_2022-07-19-18-16-39_0
- Reconstruct_2022-07-19-19-02-15_0
- Reconstruct_2022-07-18-20-34-01_0
training:
- Reconstruct_2022-07-19-20-46-08_0
- Reconstruct_2022-07-21-10-47-29_0
- Reconstruct_2022-07-19-20-06-22_0
